language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: false
  
node_js:
  - node

install:
  - npm ci

script:
  - npm run cibuild
  - npm test

after_success:
  - npm run builduipackage

before_deploy:
  - cd package

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release