language: node_js

branches:
  only:
    - master
    - /^mattm/.*$/
    - /^greenkeeper/.*$/

cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
  
node_js:
  - node

script:
  - npm run cibuild
  - npm test

before_deploy:
  - npm run builduipackage

deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd package
    - npx semantic-release