# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

cache:
  - '%AppData%\npm-cache -> appveyor.yml'
  - '%AppData%\..\Local\Cypress\Cache'
  
install:
  - npm ci

before_build:
  # Output useful info for debugging.
  - node --version
  - npm --version

build_script:
  - npm run cibuild

test_script:
  - npm run test