version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome65-ff57
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: node --version
      - run: npm --version
      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run test
      - run: npm run cibuild

      # Clone, install, and build sample application
      - run: git clone https://github.com/Microsoft/ConversationLearner-Samples -b develop ../cl-samples
      - run: cd ../cl-samples && npm ci
      - run: cd ../cl-samples && npm run build

      # Run sample
      - run: 
          command: cd ../cl-samples && npm start
          background: true

      # Run UI
      - run: 
          command: npm start
          background: true

      # Run UI e2e tests
      - run: npm run cypress -- run --browser chrome --record --key $CYPRESS_RECORD_KEY

      - store_artifacts:
          path: results
          
      - store_test_results:
          path: results
      
workflows:
  version: 2
  build:
    jobs:
      - build