let circleCiBuildNumber = +process.env.CIRCLE_BUILD_NUM
let randomIndex = Math.floor((circleCiBuildNumber % 10) / 2)
console.log(`CIRCLE_BUILD_NUM=${circleCiBuildNumber} - randomIndex=${randomIndex}`)

console.log(`CI=${process.env.CI}`)
console.log(`CI_PULL_REQUEST=${process.env.CI_PULL_REQUEST}`)
console.log(`CI_PULL_REQUESTS=${process.env.CI_PULL_REQUESTS}`)
console.log(`CIRCLE_BRANCH=${process.env.CIRCLE_BRANCH}`)
console.log(`CIRCLE_BUILD_NUM=${process.env.CIRCLE_BUILD_NUM}`)
console.log(`CIRCLE_BUILD_URL=${process.env.CIRCLE_BUILD_URL}`)
console.log(`CIRCLE_COMPARE_URL=${process.env.CIRCLE_COMPARE_URL}`)
console.log(`CIRCLE_INTERNAL_TASK_DATA=${process.env.CIRCLE_INTERNAL_TASK_DATA}`)
console.log(`CIRCLE_JOB=${process.env.CIRCLE_JOB}`)
console.log(`CIRCLE_NODE_INDEX=${process.env.CIRCLE_NODE_INDEX}`)
console.log(`CIRCLE_NODE_TOTAL=${process.env.CIRCLE_NODE_TOTAL}`)
console.log(`CIRCLE_PR_NUMBER=${process.env.CIRCLE_PR_NUMBER}`)
console.log(`CIRCLE_PR_REPONAME=${process.env.CIRCLE_PR_REPONAME}`)
console.log(`CIRCLE_PR_USERNAME=${process.env.CIRCLE_PR_USERNAME}`)
console.log(`CIRCLE_PREVIOUS_BUILD_NUM=${process.env.CIRCLE_PREVIOUS_BUILD_NUM}`)
console.log(`CIRCLE_PROJECT_REPONAME=${process.env.CIRCLE_PROJECT_REPONAME}`)
console.log(`CIRCLE_PROJECT_USERNAME=${process.env.CIRCLE_PROJECT_USERNAME}`)
console.log(`CIRCLE_PULL_REQUEST=${process.env.CIRCLE_PULL_REQUEST}`)
console.log(`CIRCLE_PULL_REQUESTS=${process.env.CIRCLE_PULL_REQUESTS}`)
console.log(`CIRCLE_REPOSITORY_URL=${process.env.CIRCLE_REPOSITORY_URL}`)
console.log(`CIRCLE_SHA1=${process.env.CIRCLE_SHA1}`)
console.log(`CIRCLE_TAG=${process.env.CIRCLE_TAG}`)
console.log(`CIRCLE_USERNAME=${process.env.CIRCLE_USERNAME}`)
console.log(`CIRCLE_WORKFLOW_ID=${process.env.CIRCLE_WORKFLOW_ID}`)
console.log(`CIRCLE_WORKING_DIRECTORY=${process.env.CIRCLE_WORKING_DIRECTORY}`)
console.log(`CIRCLECI=${process.env.CIRCLECI}`)
console.log(`HOME=${process.env.HOME}`)

