export enum AT {
    COUNTER_ADD = "COUNTER_ADD",
    COUNTER_DECREMENT = "COUNTER_DECREMENT",

    CREATE_APPLICATION_FULFILLED = "CREATE_APPLICATION_FULFILLED",
    DELETE_BLIS_APPLICATION_FULFILLED = "DELETE_BLIS_APPLICATION_FULFILLED"
} 


