/**
 * Copyright (c) Microsoft Corporation. All rights reserved.  
 * Licensed under the MIT License.
*/

import './CreateModels/AllEntityTypes.spec.js'
import './CreateModels/DisqualifyingEntities.spec.js'
import './CreateModels/EndlessLoop.spec.js'
import './CreateModels/TagAndFrog.spec.js'
import './CreateModels/Travel.spec.js'
import './CreateModels/WaitVsNoWaitActions.spec.js'
import './CreateModels/WhatsYourName.spec.js'
import './EditAndBranching/AddEndSessionAction.spec.js'
import './EditAndBranching/Branching.spec.js'
import './EditAndBranching/TagAndFrog.spec.js'
import './EditAndBranching/VerifyEditTrainingControlsAndLabels.spec.js'
import './ErrorHandling/ActionUnavailable.spec.js'
import './ErrorHandling/MissingAction.spec.js'
import './ErrorHandling/TwoConsecutiveUserInput.spec.js'
import './ErrorHandling/WaitNonWait.spec.js'
import './Log/EndlessLoop.spec.js'
import './Log/WhatsYourName.spec.js'
import './Tools/CreateModel.spec.js'
import './Tools/DeleteAllTestGeneratedModels.spec.js'
import './Tools/VerifyDoesNotContainTestMethod.spec.js'
import './Tools/VisitHomePage.spec.js'
import './Train/BookMeAFlight.spec.js'
import './Train/DisqualifyingEntities.spec.js'
import './Train/MyNameIs.spec.js'
import './Train/TagAndFrog.spec.js'
import './Train/WaitVsNoWaitActions.spec.js'
import './Train/WhatsYourName.spec.js'
import './UX/BotModelMismatch.spec.js'
import './zTemp/zTemp.spec.js'