/**
 * Copyright (c) Microsoft Corporation. All rights reserved.  
 * Licensed under the MIT License.
*/

require('./CreateModels/AllEntityTypes.spec.js')
require('./CreateModels/DisqualifyingEntities.spec.js')
require('./CreateModels/EndlessLoop.spec.js')
require('./CreateModels/TagAndFrog.spec.js')
require('./CreateModels/Travel.spec.js')
require('./CreateModels/WaitVsNoWaitActions.spec.js')
require('./CreateModels/WhatsYourName.spec.js')
require('./EditAndBranching/AddEndSessionAction.spec.js')
require('./EditAndBranching/Branching.spec.js')
require('./EditAndBranching/TagAndFrog.spec.js')
require('./EditAndBranching/VerifyEditTrainingControlsAndLabels.spec.js')
require('./ErrorHandling/ActionUnavailable.spec.js')
require('./ErrorHandling/MissingAction.spec.js')
require('./ErrorHandling/TwoConsecutiveUserInput.spec.js')
require('./ErrorHandling/WaitNonWait.spec.js')
require('./Log/EndlessLoop.spec.js')
require('./Log/WhatsYourName.spec.js')
require('./Tools/CreateModel.spec.js')
require('./Tools/DeleteAllTestGeneratedModels.spec.js')
require('./Tools/VerifyDoesNotContainTestMethod.spec.js')
require('./Tools/VisitHomePage.spec.js')
require('./Train/BookMeAFlight.spec.js')
require('./Train/DisqualifyingEntities.spec.js')
require('./Train/MyNameIs.spec.js')
require('./Train/TagAndFrog.spec.js')
require('./Train/WaitVsNoWaitActions.spec.js')
require('./Train/WhatsYourName.spec.js')
require('./UX/BotModelMismatch.spec.js')
require('./zTemp/zTemp.spec.js')